{{- if and .Values.persistence .Values.persistence.enabled }}
{{- if not .Values.persistence.existingClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "operately.fullname" . }}-data
  labels: {{- include "operately.labels" . | nindent 4 }}
  {{- if .Values.persistence.annotations }}
  annotations:
    {{- toYaml .Values.persistence.annotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- if kindIs "slice" .Values.persistence.accessModes }}
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
    {{- else }}
    - {{ .Values.persistence.accessModes | quote }}
    {{- end }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
{{- end }}
