{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (include "operately.fullname" .) .Values.secrets.name }}
  labels:
    {{- include "operately.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY_BASE: {{ required "Provide .Values.secrets.secretKeyBase or use an existing secret" (tpl .Values.secrets.secretKeyBase .) | quote }}
  DATABASE_URL: {{ required "Database must be configured via externalPostgresql or postgresql.enabled" (include "operately.database.url" .) | quote }}
{{- end }}
