apiVersion: v1
kind: Service
metadata:
  name: {{ include "operately.fullname" . }}
  labels:
    {{- include "operately.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "operately.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
