#### FOR APP OPERATELY ####
########################################################################
# Default replicaCount for operately is 1
replicaCount: 1

# Default container image more information
image:
  repository: operately/operately:v1.0.1
  pullPolicy: IfNotPresent
  tag: "v1.0.1"

# Default service
service:
  # ClusterIP | NodePort
  type: ClusterIP

  # ClusterIP example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  # NodePort example
  # ports:
  #   - protocol: TCP
  #     port: 80
  #     targetPort: 3000    
  #     nodePort: 32000
  

# TODO
ingress:
  enabled: false

resources:
  requests:
    cpu: 200m
    memory: 128Mi 
  limits:
    cpu: 500m
    memory: 512Mi


# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# Horizontal Pod Autoscaler configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

persistence:
  enabled: true
  size: 2Gi
  storageClassName: "longhorn"       # e.g., "longhorn" (empty = cluster default)
  accessModes: ["ReadWriteOnce"]

  # Directories inside the single PVC
  layout:
    root: /data              # where initContainer mounts the PVC
    media: media             # -> /data/media
    screenshots: screenshots # -> /data/screenshots
    certs: certs             # -> /data/certs
########################################################################


# TODO this one
postgresql:
  enabled: false

externalPostgres:
  enabled: true

minio: 
  enabled: false

externalMinio:
  enabled: true