apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rwmarkable.fullname" . }}
  labels:
    {{- include "rwmarkable.labels" . | nindent 4 }}
data:
  PORT: {{ quote (toString .Values.service.port) }}
  NODE_ENV: {{ quote .Values.env.NODE_ENV }}
  {{- if .Values.env.HTTPS }}
  HTTPS: {{ quote .Values.env.HTTPS }}
  {{- end }}
  {{- if .Values.env.SSO_MODE }}
  SSO_MODE: {{ quote .Values.env.SSO_MODE }}
  {{- end }}
  {{- if .Values.env.OIDC_ISSUER }}
  OIDC_ISSUER: {{ quote .Values.env.OIDC_ISSUER }}
  {{- end }}
  {{- if .Values.env.OIDC_CLIENT_ID }}
  OIDC_CLIENT_ID: {{ quote .Values.env.OIDC_CLIENT_ID }}
  {{- end }}
  {{- if .Values.env.APP_URL }}
  APP_URL: {{ quote .Values.env.APP_URL }}
  {{- end }}

