apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rwmarkable.fullname" . }}
  labels:
    {{- include "rwmarkable.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rwmarkable.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rwmarkable.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
        fsGroupChangePolicy: {{ .Values.podSecurityContext.fsGroupChangePolicy | quote }}
      {{- end }}
      containers:
        - name: rwmarkable
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "rwmarkable.fullname" . }}
          env:
            {{- range .Values.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.extraSecretEnv }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "rwmarkable.fullname" $) $.Values.secrets.name }}
                  key: {{ .key }}
            {{- end }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: storage
              mountPath: {{ .Values.persistence.mountPathData }}
            - name: storage
              mountPath: {{ .Values.persistence.mountPathConfig }}
              readOnly: {{ .Values.persistence.configReadOnly | default true }}
            {{- end }}
            {{- if .Values.persistence.cache.enabled }}
            - name: cache
              mountPath: {{ .Values.persistence.cache.mountPath }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 6
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "rwmarkable.fullname" . }}-storage
        {{- end }}
        {{- if .Values.persistence.cache.enabled }}
        - name: cache
          persistentVolumeClaim:
          claimName: {{ include "rwmarkable.fullname" . }}-cache
        {{- end }}
